### ISSUE TITLE
Outmoded advice on password complexity (18)

### ISSUE THREAD

**Issue by kraln** [openiotmark/iotmark-principles#1]
Snip: "The company’s sign in process encourages its customers to choose passwords which include alphanumeric characters, special symbols, and are of significant permitted length."

This is an oft repeated, sadly incorrect security concept. Please do not bake this into the IOT Mark Standard. The most important thing for passwords is that they should have the most entropy possible.

References: 

- https://pthree.org/2011/03/07/strong-passwords-need-entropy/
- https://arstechnica.com/information-technology/2013/06/password-complexity-rules-more-annoying-less-effective-than-length-ones/
- http://crambler.com/password-security-why-secure-passwords-need-length-over-complexity/

**Comment by tamberg** [comment]
Replaced all security principles with a higher level version, see https://github.com/openiotmark/iotmark-principles/issues/3:
https://github.com/openiotmark/iotmark-principles/tree/develop#security
