### ISSUE TITLE
The security principles and assessment criteria are too technical

### ISSUE THREAD

**Issue by cetome** [openiotmark/iotmark-principles#3]
The principles are too technical and too specific. The current criteria might evolve in time (i.e. encryption might be broken) and should not constraint a solution to implement one specific technology.

Suggestion to use 5 security principles and integrate the current ones as assessment criteria:
1. The organisation should implement security in its processes (must have)
2. The product follows the principle of security by design (must have)
3. The product integrates security by default (nice to have)
4. A risk assessment was performed on the product to ensure it is secure against IoT threats, including: [list of IoT threats] (must have)
5. The organisation offers security support for the entire lifetime of the product (must have)

**Comment by tamberg** [comment]
[cedriclb on Slack] The content would be the current principles:
1. Demonstrate training, regular security assessment, security requirements for their suppliers, threat intelligence
2. Define security requirements, strong crypto, provide security support via OTA update (see 5), integrate the security of dependencies (see 5), secure firmware
3. User need to change the password at first run, no unencrypted comm, no unneeded open service 
4. Ensure pentest demonstrates the security of the product and its backend (OWASP Top 10, secure backend)
5. Engagement to provide security OTA update within a defined timeframe, secure architecture, secure configuration

**Comment by tamberg** [comment]
Done https://github.com/openiotmark/iotmark-principles/tree/develop#security
